language: csharp

sudo: false  # use the new container-based Travis infrastructure 

mono: 5.12.0

dotnet: 2.2.100

install:

  # workaround for missing .net 4.5 targing pack

  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - sudo sudo curl -s -L https://entrust.com/root-certificates/entrust_l1k.cer -o /usr/local/share/ca-certificates/entrust_l1k.crt
  - sudo update-ca-certificates
  - sudo dotnet tool install fake-cli --tool-path /bin
  - sudo chmod -R a+rw /home/travis/.nuget
  - sudo chmod -R a+rw /tmp


before_install:
  - chmod +x build.sh


include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet : 2.2.100
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet : 2.2.100
      dist: trusty
      sudo: required
      
script: 
  - ./build.sh All
