image: Visual Studio 2019
install:
  - cinst fake
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd All
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
